version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: "e90dc767-c019-445d-aa9c-f631fad42821"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
