version: 1.0
app:
  instances:
    min: 1
    max: 2
  version: "57e76e85-df10-4f0f-a86a-90161a63075b"
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
