version: 1.0
app:
  instances: 1
  version: 1.0-SNAPSHOT-20230721173538
  env:
    - name: JVM_ARGS
      value: "-DenvironmentType=stage"
    - name: io_openliberty_sample_system_inMaintenance
      value: "false"
